//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OID.LegacySoapService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oplataidostavka.ru/DataProvider/", ConfigurationName="ServiceReference1.DataProviderSoap")]
    public interface DataProviderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oplataidostavka.ru/DataProvider/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Query(string queryAsXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oplataidostavka.ru/DataProvider/Query", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryAsync(string queryAsXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataProviderSoapChannel : OID.LegacySoapService.ServiceReference1.DataProviderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataProviderSoapClient : System.ServiceModel.ClientBase<OID.LegacySoapService.ServiceReference1.DataProviderSoap>, OID.LegacySoapService.ServiceReference1.DataProviderSoap {
        
        public DataProviderSoapClient() {
        }
        
        public DataProviderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataProviderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataProviderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataProviderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Query(string queryAsXml) {
            return base.Channel.Query(queryAsXml);
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(string queryAsXml) {
            return base.Channel.QueryAsync(queryAsXml);
        }
    }
}
